spring:
  application:
    name: ap-service-gcp
  main:
    web-application-type: servlet
  cloud:
    gcp:
      firestore:
        project-id: ${GOOGLE_CLOUD_PROJECT_ID}
        emulator:
          enabled: false
#      credentials:
#        location=:classpath:credentials.json
server:
  port: ${PORT:8080}
