spring:
  application:
    name: ap-service-gcp
  main:
    web-application-type: servlet
  cloud:
    gcp:
      firestore:
        project-id: ${GOOGLE_CLOUD_PROJECT_ID}
        emulator:
          enabled: false
      cloud-run-app-name: "${CLOUD_RUN_APP_NAME:cloud-run-app}"
      pubsub:
        service-account-email: "${SERVICE_ACCOUNT_EMAIL:526165826130-compute@developer.gserviceaccount.com}"


#      credentials:
#        location=:classpath:credentials.json
server:
  port: ${PORT:8080}
